import React, { Component } from 'react';
import Navbar from '../navbar/index'
import Footer from '../footer/index'
class Privacy extends Component {
    render() {
        return (
            <div className="contact-us">
                <Navbar />
                <div className="container" style={{ paddingTop: "20px" }}>

                    <div className="row">
                        <div className="col-md-4">
                            <div className="container">
                                <div >
                                    <h5 className="headline margin-bottom-30">Find Us There</h5>
                                    <div className="sidebar-textbox">
                                        <p>LOUVAIN-LA-NEUVE,City Centre Place de L'universite 16 Louvain-la-Neuve</p>
                                        <ul className="contact-details">
                                            <li><i className="material-icons">phone</i> <strong>Phone:</strong> <span>(+32) 470776403 </span></li>
                                            <li><i className="material-icons">web</i> <strong>Web:</strong> <span><a href="#">www.tamtamtools.com</a></span></li>
                                            <li><i className="material-icons">email</i> <strong>E-Mail:</strong> <span><a href="#">support@tamtamtools.com</a></span></li>
                                        </ul>
                                    </div>
                                    <div className="clearfix"></div>
                                </div>
                                <div className="clearfix"></div>
                            </div>
                        </div>

                        <div className="col-md-8">

                            <section id="contact">
                                <h5 className="headline margin-bottom-35">Privacy policy</h5>

                                <div id="contact-message">
                                    <p>  Privacy Policy Effective date: April 27, 2018</p>
                                    <p> TamTamTools BVBA ("us", "we", or "our") operates the www.tamtamtools.com website and the TamTamToolsApp mobile application (the "Service").
This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
Definitions</p>
                                    <p> Personal Data</p>
                                    Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                                    <p> Usage Data</p>
                                    Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                                    <p> Cookies</p>
                                    Cookies are small pieces of data stored on a User’s device.
                                    <p> Data Controller</p>
                                    Data Controller means a person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed.
For the purpose of this Privacy Policy, we are a Data Controller of your data.
                                    <p>Data Processor (or Service Providers)</p>
                                    Data Processor (or Service Provider) means any person (other than an employee of the Data Controller) who processes the data on behalf of the Data Controller.
We may use the services of various Service Providers in order to process your data more effectively.
                                    <p>Data Subject</p>
                                    Data Subject is any living individual who is the subject of Personal Data.
                                    <p>User</p>
                                    The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
Information Collection And Use
We collect several different types of information for various purposes to provide and improve our Service to you.
Types of Data Collected
                                    <p>Personal Data</p>
                                    While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
                                    <div>•	Email address</div>
                                    <div>•	First name and last name</div>
                                    <div>•	Phone number</div>
                                    <div>•	Address, State, Province, ZIP/Postal code, City</div>
                                    <div>•	Cookies and Usage Data</div>
                                    We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.
                                    <p>Usage Data</p>
                                    We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
When you access the Service by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
                                    <p>Location Data</p>
                                    We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.
You can enable or disable location services when you use our Service at any time, through your device settings.
                                    <p>Tracking Cookies Data</p>
                                    We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                                    <p>Examples of Cookies we use:</p>
                                    <div>•	Session Cookies. We use Session Cookies to operate our Service.</div>
                                    <div>•	Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</div>
                                    <div>•	Security Cookies. We use Security Cookies for security purposes.</div>
                                    <p>Use of Data</p>
                                    TamTamTools BVBA uses the collected data for various purposes:
                                    <div>•	To provide and maintain our Service</div>
                                    <div>•	To notify you about changes to our Service</div>
                                    <div>•	To allow you to participate in interactive features of our Service when you choose to do so</div>
                                    <div>•	To provide customer support</div>
                                    <div>•	To gather analysis or valuable information so that we can improve our Service</div>
                                    <div>•	To monitor the usage of our Service</div>
                                    <div>•	To detect, prevent and address technical issues</div>
                                    <div>•	To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</div>
                                    <p>Retention of Data</p>
                                    TamTamTools BVBA will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
TamTamTools BVBA will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
<p>Transfer Of Data</p>
                                    Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
If you are located outside Belgium and choose to provide information to us, please note that we transfer the data, including Personal Data, to Belgium and process it there.
Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
TamTamTools BVBA will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
<p>Disclosure Of Data</p>
                                    Disclosure for Law Enforcement
Under certain circumstances, TamTamTools BVBA may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
Legal Requirements
TamTamTools BVBA may disclose your Personal Data in the good faith belief that such action is necessary to:
                                    <div>•	To comply with a legal obligation</div>
                                    <div>•	To protect and defend the rights or property of TamTamTools BVBA</div>
                                    <div>•	To prevent or investigate possible wrongdoing in connection with the Service</div>
                                    <div>•	To protect the personal safety of users of the Service or the public</div>
                                    <div>•	To protect against legal liability</div>
                                    <p>Security Of Data</p>
                                    The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
"Do Not Track" Signals
We do not support Do Not Track ("DNT"). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
<p>Your Rights</p>
                                    TamTamTools BVBA aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
Whenever made possible, you can update your Personal Data directly within your account settings section. If you are unable to change your Personal Data, please contact us to make the required changes.
If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
In certain circumstances, you have the right:
<div>•	To access and receive a copy of the Personal Data we hold about you</div>
                                    <div>•	To rectify any Personal Data held about you that is inaccurate</div>
                                    <div>•	To request the deletion of Personal Data held about you</div>
                                    You have the right to data portability for the information you provide to TamTamTools BVBA. You can request to obtain a copy of your Personal Data in a commonly used electronic format so that you can manage and move it.
Please note that we may ask you to verify your identity before responding to such requests.
<p>Service Providers</p>
                                        We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                                        <p>Analytics</p>
                                        We may use third-party Service Providers to monitor and analyze the use of our Service.
                                        <p>Google Analytics</p>
                                        Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.
For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: http://www.google.com/intl/en/policies/privacy/
                                        <p>Behavioral Remarketing</p>
                                        TamTamTools BVBA uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.
                                        <p>Google AdWords</p>
                                        Google AdWords remarketing service is provided by Google Inc.
You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page: http://www.google.com/settings/ads
Google also recommends installing the Google Analytics Opt-out Browser Add-on - https://tools.google.com/dlpage/gaoptout - for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics.
For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: http://www.google.com/intl/en/policies/privacy/
                                    <p>Twitter</p>
                                        Twitter remarketing service is provided by Twitter Inc.
You can opt-out from Twitter's interest-based ads by following their instructions: https://support.twitter.com/articles/20170405
You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page: https://twitter.com/privacy
                                    <p>Facebook</p>
                                        Facebook remarketing service is provided by Facebook Inc.
You can learn more about interest-based advertising from Facebook by visiting this page: https://www.facebook.com/help/164968693837950
To opt-out from Facebook's interest-based ads follow these instructions from Facebook: https://www.facebook.com/help/568137493302217
Facebook adheres to the Self-Regulatory Principles for Online Behavioral Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA http://www.aboutads.info/choices/, the Digital Advertising Alliance of Canada in Canada http://youradchoices.ca/ or the European Interactive Digital Advertising Alliance in Europe http://www.youronlinechoices.eu/, or opt-out using your mobile device settings.
For more information on the privacy practices of Facebook, please visit Facebook's Data Policy: https://www.facebook.com/privacy/explanation
 <p>Pinterest</p>
                                        Pinterest remarketing service is provided by Pinterest Inc.
You can opt-out from Pinterest's interest-based ads by enabling the "Do Not Track" functionality of your web browser or by following Pinterest instructions: http://help.pinterest.com/en/articles/personalization-and-data
You can learn more about the privacy practices and policies of Pinterest by visiting their Privacy Policy page: https://about.pinterest.com/en/privacy-policy
 <p>Payments</p>
                                        We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).
We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.
The payment processors we work with are:
 <p>PayPal or Braintree</p>
                                        Their Privacy Policy can be viewed at https://www.paypal.com/webapps/mpp/ua/privacy-full
Links To Other Sites
Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
Children's Privacy
Our Service does not address anyone under the age of 13 ("Children").
We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
Changes To This Privacy Policy
We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.
You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
 <p>Contact Us</p>
                                        If you have any questions about this Privacy Policy, please contact us:
<div>•	By email: office@tamtamtools.com</div>



                                </div>

                            </section>
                                </div>
                        </div>

                        </div>
                        <style>{`
                        #contact textarea {
                            min-height: 200px;
                            margin: 15px 0 25px 0;
                        }

                        #contact input {
                            margin-bottom: 25px;
                        }
                        .contact-us input, .contact-us textarea{
                            border:1px solid lightgrey !important;
                            border-radius:5px !important;
                            padding-left:10px !important;
                        }
                        .contact-us input::placeholder{
                            padding-left:10px !important;
                        }
                        .loader { margin-left: 15px; }
                        .submit.disabled:hover,
                        .submit.disabled { background-color: #e8e8e8; color: #333; }

                        #contact input.button.submit {
                            margin-bottom: 10px;
                            line-height: 18px;
                            height: 49px;
                            transition: all 0.25s !important;
                        }


                        #contact input[type="submit"].submit:hover {
                            opacity: 0.92;
                        }

                        .contact-sent {
                            background-color: #EBF6E0;
                            color: #5f9025;
                            padding: 20px 26px;
                            margin-bottom: 30px;
                            border-radius: 3px;
                        }


                        /* Office Address Box */
                        .office-address {
                            text-align: center;
                            position: relative;
                            color: #fff;
                            display: table-cell;
                            vertical-align: middle;
                            height: 100%;
                        }

                        .office-address ul {
                            list-style: none;
                            font-size: 18px;
                            padding: 0;
                            line-height: 30px;
                        }

                        .office-address h3 {
                            font-size: 28px;
                            color: #fff;
                            margin-top: 0;
                        }

                        .office-address h3:after {
                            content: "";
                            height: 2px;
                            width: 50px;
                            position: relative;
                            display: block;
                            background-color: #66676b;
                            margin: 20px auto;
                            border-radius: 2px;
                        }

                        .address-container {
                            background-color: #2b2c30;
                            background-size: 100%;
                            background-position: 50% 50%;
                            background-repeat: no-repeat;
                            background-size: cover;
                            display: table;
                            width: 100%;
                            position: relative;
                            height: 100%
                        }

                        .address-container:before {
                            content: "";
                            height: 100%;
                            width: 100%;
                            position: absolute;
                            top:0;
                            left:0;
                            display: block;
                            background-color: #333;
                            opacity: 0.7;
                        }


                        /* Google Maps */
                        .contact-map { display: flex; }
                        .contact-map #singleListingMap-container { flex: 1; position: relative; padding-top: 0; }
                        .contact-map .address-box-container { flex: 0 auto; width: 440px; height: 450px; }
                        .contact-map #singleListingMap-container #singleListingMap { height: 100%; width: 100%; }

                        @media (min-width: 1680px) { .contact-map .address-box-container { height: 480px; } }
                        @media (max-width: 1440px) { .contact-map .address-box-container { height: 420px; } }


                        /* Contact Details */
                        .sidebar-textbox {
                            display: inline-block;
                            width: 100%;
                            padding-right: 40px;
                        }

                        .sidebar-textbox.color {
                            background-color: #666;
                            color: #fff;
                        }

                        .sidebar-textbox.color h4 {color: #fff;}
                        .sidebar-textbox h4 {
                            font-size: 16px;
                            margin: 0;
                            padding: 0;
                            margin-bottom: 16px;
                        }

                        .sidebar-textbox span { color: #666; display: inline-block; }
                        .sidebar-textbox.color span { color: #fff; }

                        .sidebar-textbox ul.contact-details {
                            list-style: none;
                            padding: 5px 0 0 0;
                        }

                        .sidebar-textbox ul.contact-details strong {
                            font-weight: 500;
                        }

                        .sidebar-textbox ul.contact-details li {
                            text-align: left;
                            padding-left: 60px;
                            position: relative;
                            width: 100%;
                            display: inline-block;
                            margin: 10px 0;
                            line-height: 24px;
                        }

                        .sidebar-textbox ul.contact-details li a { color: #66676b; }

                        .sidebar-textbox ul.contact-details li strong {
                            display: block;
                            color: #333;
                        }

                        .sidebar-textbox ul.contact-details li i {
                            height: 100%;
                            position: absolute;
                            left: 0;
                            font-size: 32px;
                            color: #333;
                            top: 10px
                        }

                `}
                        </style>
                        <Footer />

                    </div>
                    );
    }
}

export default Privacy;
